---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: apps
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: k3s/apps
    repoURL: https://github.com/MrVym/Geode.git
    targetRevision: master
