---
kind: Kustomization
namespace: argocd

resources:
  - namespace.yml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.11.2
  - ingress.yml
  - apps.yml

patches:
  - path: patch-argocd-cm.yml
