#cloud-config
package_upgrade: true
packages:
  - qemu-guest-agent

timezone: Europe/Paris

preserve_hostname: true

users:
  - default
  - name: vym
    groups: sudo
    passwd: "test"
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:

      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCU9W23J84wcMbCBTscwGllcSie9pf+uwvo9giaSAEiXX93fSx6RWRqV0GgrZEzhIcykydpaqjt3YuJu87HJUaonfEPvDeMdzzolMo603l76a4IKxDXQZhjjyy9q7k/TfItWa17hH38MOrhinQPY+s4p4w8S7ML7eQFRqBtVu6awBr44umkHogh7he19Da2NG+t4FzAPC8IvhGQLLxEGCkrx53JhounS201U5TC1EplyR4OukEUKlTtrQrxJZfk+OAelcQQtYju4pOgMZTA/h+d7QwL61nAwxgCtA6BcFW5HxYMIikDZ1BiV2pClZCOKbb4ulgdFV/HL2c/+nDZf0fv openpgp:0x8F7BCA15

      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJTpb80oe0sQTdKrxBZVsgQDtw1oOvxBosu+FhilIG6g vym@opale


runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart sshd.service

power_state:
  mode: reboot
  message: Rebooting after cloud-init completion
  condition: true
