#cloud-config
package_upgrade: true
packages:
  - qemu-guest-agent

timezone: Europe/Paris

preserve_hostname: true

runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart sshd.service

power_state:
  mode: reboot
  message: Rebooting after cloud-init completion
  condition: true
